spring:
  cloud:
    gateway:
      routes:
        - id: WIKI-PRODUCER
          uri : lb://WIKI-PRODUCER
          predicates :
           - Path=/producer/**

server:
  port: 8084
eureka:
  instance:
    hostname: localhost
